### ISSUE TITLE
Home page bug

### ISSUE THREAD

**Issue by Chadani7** [Dips2020/Colaborative_Development#54]
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/3596969d-0572-46de-b48f-c9f2e1937dd3)

# There is no need of user role pop up and it should be add user role by user themselves from profile page.

**Comment by Dips2020** [comment]
![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/ce5661ea-0efa-4fa4-b305-8f9b65f17938)

# Now the pop-up will not be displayed at the beginning. 
# Solved
