### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by Chadani7** [Dips2020/Colaborative_Development#55]
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/c9d0dda0-afad-421e-85a9-31f3b6be31f5)

# While navigating to the admin page, it should not be opened directly. First, it should ask admin password and then redirect to the Admin dashboard.

**Comment by Dips2020** [comment]
![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/3019fbe6-46c2-4c0c-8bb0-ea5cff4618d6)
# It asks for the admin password.
![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/cd202965-fac1-4ebb-b118-93132dd66836)
# If the password does not match then it alerts the user.
![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/1bea35e5-a867-4997-aaa4-07150832229e)
# Solved
