### ISSUE TITLE
Logout problem

### ISSUE THREAD

**Issue by Chadani7** [Dips2020/Colaborative_Development#56]
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/8c8f3eec-2941-437e-9960-4be770c2e4b8)

# While Signing out, It is not working. User is not being signed out

**Comment by Dips2020** [comment]
![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/18a773fc-2cc8-444a-9eb1-0e2a07774442)

![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/244c05c2-3cef-4469-898b-acad53a4bd95)

# Solved
