### ISSUE TITLE
Add to cart not working

### ISSUE THREAD

**Issue by Chadani7** [Dips2020/Colaborative_Development#58]
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/68e4fe14-0bff-4bfd-8f63-d391a374bfbc)

![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/865911ce-aedc-44bf-8c65-aa3bd57ca8a1)

# As shown in the above two screenshots, While adding product to the cart, Product is not displaying to the cart page

**Comment by Dips2020** [comment]
![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/72ae34c3-42b6-48ce-adbc-fe6716d95157)

# Stored in database

![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/e8d19e38-024f-41bc-91fb-4433cf5a9887)

# Fetched from database and displayed in cart page

# SOLVED
