### ISSUE TITLE
User profile bug

### ISSUE THREAD

**Issue by Chadani7** [Dips2020/Colaborative_Development#59]
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/dcb5dcc8-ee03-4007-a6e4-386236eb66ad)

# In user profile page, User info is not displayed.  Changing role is also not working.

**Comment by Dips2020** [comment]
![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/5f663342-e92e-4e38-a9f9-0e172b39c933)

# Solved this user basic information displaying in profile page and changing role functionality too.
