### ISSUE TITLE
Admin verification bug

### ISSUE THREAD

**Issue by Chadani7** [Dips2020/Colaborative_Development#60]
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/f546febb-a8ab-483a-bce9-2e96ce9dfc2a)

![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/9e853c35-6fb7-4232-8514-cf8893264178)

# Admin cant verify user either accept user or delete user

**Comment by Dips2020** [comment]
![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/499e7765-4a1a-44f3-ab0c-c334361697e4)

![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/58a91058-d5c4-4b5b-ab06-b84973c0454e)

![image](https://github.com/Dips2020/Colaborative_Development/assets/88276236/af0095ac-2482-46dd-8e3c-69d1f03c7362)

# Solved admin verification
