### ISSUE TITLE
 Cart  items  total count bug

### ISSUE THREAD

**Issue by Chadani7** [Dips2020/Colaborative_Development#69]
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/c27237e9-ed02-42a3-b1d8-24810c8bda43)

# Encountering  a  problem in add to cart in  total count  of products

**Comment by 10jing3** [comment]
![image](https://github.com/Dips2020/Colaborative_Development/assets/129353020/b670c9ae-9654-45cb-81fb-2d8174780a83)



![Screenshot 2024-05-18 214842](https://github.com/Dips2020/Colaborative_Development/assets/129353020/35f88e60-173b-42ce-ae4d-7befe4f60134)

The bug has been fixed .
