### ISSUE TITLE
Each product count bug

### ISSUE THREAD

**Issue by Chadani7** [Dips2020/Colaborative_Development#70]
![image](https://github.com/Dips2020/Colaborative_Development/assets/164293860/5ff3af40-49b6-4f20-baf3-5467b93021fd)

#  There is a problem in each items count.

**Comment by 10jing3** [comment]
![image](https://github.com/Dips2020/Colaborative_Development/assets/129353020/990b8d63-9681-4e24-965e-c5445b8519cc)

![Screenshot 2024-05-18 230624](https://github.com/Dips2020/Colaborative_Development/assets/129353020/bfc937c3-bc51-405c-9514-f924425ae3a5)

the Bug has been fixed
